import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, Plus, Search, Trash2, UserRound, UsersRound } from "lucide-react";
import { Button, Field, Input, Select, TextArea } from "../components/ui";

const money=(value)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(Number(value||0));

export default function Classes({state,derived,actions}){
 const defaults=state.settings; const [mode,setMode]=useState("group"); const [groupId,setGroupId]=useState(""); const [studentId,setStudentId]=useState(""); const [date,setDate]=useState(defaults.asOfDate); const [startTime,setStartTime]=useState(""); const [title,setTitle]=useState(""); const [hours,setHours]=useState(defaults.defaultClassHours); const [notes,setNotes]=useState(""); const [roster,setRoster]=useState({}); const [historyQuery,setHistoryQuery]=useState(""); const [saving,setSaving]=useState(false);
 const eligibleIndividuals=state.students.filter((s)=>s.status==="Active"&&s.isIndividual);
 const groupStudents=useMemo(()=>state.students.filter((s)=>s.status==="Active"&&(s.groupIds||[]).includes(groupId)),[groupId,state.students]);
 const selectedStudents=mode==="group"?groupStudents.filter((s)=>roster[s.id]?.included!==false):(state.students.find((s)=>s.id===studentId)?[state.students.find((s)=>s.id===studentId)]:[]);
 const updateRoster=(id,patch)=>setRoster((current)=>({...current,[id]:{included:true,attendance:"P",paid:false,...current[id],...patch}}));
 const classStatus=date>defaults.asOfDate?"Scheduled":"Completed";
 const save=async()=>{if(!selectedStudents.length){actions.notify(mode==="group"?"Choose a group with students.":"Choose an individual student.","error");return;}setSaving(true);const amount=Number(hours||defaults.defaultClassHours)*Number(defaults.hourlyRate);const rows=selectedStudents.map((student)=>{const item={included:true,attendance:"P",paid:false,...roster[student.id]};return{classDate:date,startTime,classTitle:title,groupId:mode==="group"?groupId:"",studentId:student.id,classStatus,attendance:classStatus==="Completed"?item.attendance:null,hours:Number(hours),amountPaid:item.paid?amount:0,paymentDate:item.paid?(date>defaults.asOfDate?defaults.asOfDate:date):null,paymentMethod:item.paid?"Cash":"",notes};});if(await actions.addClassLogs(rows)){setTitle("");setNotes("");setRoster({});}setSaving(false);};
 const sessions=useMemo(()=>{const map=new Map();for(const row of derived.classLog){const key=[row.classDate,row.startTime||"",row.groupId||`student:${row.studentId}`,row.classTitle||""].join("|");if(!map.has(key))map.set(key,{...row,rows:[]});map.get(key).rows.push(row);}return[...map.values()].filter((session)=>[session.classTitle,session.groupName,session.studentName,session.classDate].join(" ").toLowerCase().includes(historyQuery.toLowerCase())).sort((a,b)=>`${b.classDate} ${b.startTime||""}`.localeCompare(`${a.classDate} ${a.startTime||""}`));},[derived.classLog,historyQuery]);
 return <div className="page"><div className="page-heading"><div><h1>Classes</h1><p>Schedule, log, and review group or one-on-one classes.</p></div></div><section className="class-layout"><article className="class-form-panel"><div className="segmented"><button type="button" className={mode==="group"?"active":""} onClick={()=>setMode("group")}><UsersRound size={17}/>Group</button><button type="button" className={mode==="individual"?"active":""} onClick={()=>setMode("individual")}><UserRound size={17}/>Individual</button></div>{mode==="group"?<Field label="Group" required><Select value={groupId} onChange={(e)=>{setGroupId(e.target.value);setRoster({});}}><option value="">Choose group</option>{state.groups.map((g)=><option key={g.id} value={g.id}>{g.name}</option>)}</Select></Field>:<Field label="Individual student" required><Select value={studentId} onChange={(e)=>setStudentId(e.target.value)}><option value="">Choose student</option>{eligibleIndividuals.map((s)=><option key={s.id} value={s.id}>{s.fullName}</option>)}</Select></Field>}
 <div className="form-grid two-columns"><Field label="Date" required><Input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></Field><Field label="Start time" hint="Optional"><Input type="time" value={startTime} onChange={(e)=>setStartTime(e.target.value)}/></Field></div><div className="form-grid two-columns"><Field label="Class title / topic" hint={mode==="group"?"If empty, the group name is shown.":"Optional"}><Input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="e.g. Conversation practice"/></Field><Field label="Duration (hours)"><Input type="number" min="0" step="0.25" value={hours} onChange={(e)=>setHours(e.target.value)}/></Field></div><div className="rate-note"><span>Rate</span><strong>{money(defaults.hourlyRate)} MXN / hour</strong><span>Expected per student: {money(Number(hours||0)*defaults.hourlyRate)}</span></div>
 {mode==="group"&&groupId?<div className="roster-editor"><h3>Roster</h3>{groupStudents.map((student)=>{const item={included:true,attendance:"P",paid:false,...roster[student.id]};return <div className="roster-line" key={student.id}><label><input type="checkbox" checked={item.included} onChange={(e)=>updateRoster(student.id,{included:e.target.checked})}/><strong>{student.fullName}</strong></label><Select value={item.attendance} onChange={(e)=>updateRoster(student.id,{attendance:e.target.value})} disabled={!item.included||classStatus!=="Completed"}><option value="P">Present</option><option value="L">Late</option><option value="A">Absent</option><option value="E">Excused</option></Select><label className="paid-check"><input type="checkbox" checked={item.paid} onChange={(e)=>updateRoster(student.id,{paid:e.target.checked})} disabled={!item.included}/><span>Paid</span></label></div>})}{!groupStudents.length?<p>This group has no active students.</p>:null}</div>:null}
 {mode==="individual"&&studentId?<label className="individual-paid"><input type="checkbox" checked={Boolean(roster[studentId]?.paid)} onChange={(e)=>updateRoster(studentId,{paid:e.target.checked})}/><CheckCircle2 size={17}/>Paid {date>defaults.asOfDate?"in advance":"for this class"}</label>:null}<Field label="Notes"><TextArea rows="2" value={notes} onChange={(e)=>setNotes(e.target.value)}/></Field><Button variant="primary" icon={Plus} onClick={save} disabled={saving}>{saving?"Saving…":"Save class"}</Button></article>
 <article className="history-panel"><div className="history-head"><div><h2>Class history</h2><p>{sessions.length} sessions</p></div><label className="mini-search"><Search size={15}/><input value={historyQuery} onChange={(e)=>setHistoryQuery(e.target.value)} placeholder="Search"/></label></div><div className="session-list">{sessions.map((session)=><div className="session-card" key={`${session.id}-${session.rows.length}`}><div className="session-date"><CalendarDays size={17}/><span><strong>{session.classDate}</strong><small>{session.startTime||"Time not set"}</small></span></div><div className="session-copy"><strong>{session.classTitle||session.groupName||session.studentName||"Individual class"}</strong><small>{session.groupName?`Group ${session.groupName}`:session.rows.map((r)=>r.studentName).join(", ")}</small></div><div className="session-summary"><span>{session.rows.filter((r)=>["P","L"].includes(r.attendance)).length}/{session.rows.length} attended</span><strong>{money(session.rows.reduce((sum,r)=>sum+Number(r.recognizedPaid||0),0))}</strong></div><button type="button" aria-label="Delete class session" onClick={()=>{if(confirm("Delete every student record in this class session?"))session.rows.forEach((row)=>actions.deleteClassLog(row.id));}}><Trash2 size={16}/></button></div>)}{!sessions.length?<div className="empty-box"><Clock3 size={27}/><h2>No class records</h2><p>Your saved group and individual classes will appear here.</p></div>:null}</div></article></section></div>;
}
