import { useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronRight, Clock3, Pencil, Plus, Search, Trash2, TrendingUp, UsersRound } from "lucide-react";
import { Button, Drawer, Field, Input, TextArea } from "../components/ui";

const EMPTY = { id: "", name: "", grade: "", subject: "", scheduleRoom: "", plannedSessionsPerMonth: 8, assistantContact: "", notes: "" };
const initials = (name) => String(name || "?").split(/\s+/).map((part) => part[0]).slice(0,2).join("").toUpperCase();
const money = (value) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(Number(value || 0));
const pct = (value) => value == null ? "—" : `${Math.round(value * 100)}%`;

function GroupEditor({ draft, setDraft }) { return <form className="drawer-form" onSubmit={(e) => e.preventDefault()}><Field label="Group name" required><Input value={draft.name} onChange={(e) => setDraft({ ...draft, name:e.target.value })}/></Field><div className="form-grid two-columns"><Field label="Grade"><Input value={draft.grade} onChange={(e) => setDraft({ ...draft, grade:e.target.value })}/></Field><Field label="Subject"><Input value={draft.subject} onChange={(e) => setDraft({ ...draft, subject:e.target.value })}/></Field></div><Field label="Schedule"><Input value={draft.scheduleRoom} onChange={(e) => setDraft({ ...draft, scheduleRoom:e.target.value })} placeholder="Tuesdays · 4:00 PM"/></Field><Field label="Planned sessions / month"><Input type="number" min="0" value={draft.plannedSessionsPerMonth} onChange={(e) => setDraft({ ...draft, plannedSessionsPerMonth:Number(e.target.value) })}/></Field><Field label="Assistant / contact"><TextArea rows="2" value={draft.assistantContact} onChange={(e) => setDraft({ ...draft, assistantContact:e.target.value })}/></Field><Field label="Notes"><TextArea rows="3" value={draft.notes} onChange={(e) => setDraft({ ...draft, notes:e.target.value })}/></Field></form>; }

export default function Groups({ state, derived, actions, navigate }) {
  const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState(""); const [draft,setDraft]=useState(null); const [membersOpen,setMembersOpen]=useState(false);
  const group=state.groups.find((item)=>item.id===selectedId); const summary=derived.groups.find((item)=>item.id===selectedId)||{};
  const members=useMemo(()=>state.students.filter((student)=>(student.groupIds||[]).includes(selectedId)),[selectedId,state.students]);
  const filtered=state.groups.filter((item)=>[item.name,item.subject,item.grade,item.scheduleRoom].join(" ").toLowerCase().includes(query.toLowerCase()));
  const save=async()=>{if(await actions.upsertGroup(draft)){setDraft(null);}};
  const toggleMember=async(student)=>actions.upsertStudent({...student,groupIds:(student.groupIds||[]).includes(selectedId)?student.groupIds.filter((id)=>id!==selectedId):[...(student.groupIds||[]),selectedId]});
  if(group) return <div className="page detail-page"><button className="back-link" type="button" onClick={()=>setSelectedId("")}><ArrowLeft size={17}/>Groups</button><section className="detail-hero"><div className="group-emblem">{group.name.slice(0,1).toUpperCase()}</div><div className="detail-identity"><h1>{group.name}</h1><p>{group.scheduleRoom||"Schedule not set"} · {members.length} students {group.grade?`· ${group.grade}`:""}</p></div><div className="hero-actions"><Button icon={Plus} onClick={()=>setMembersOpen(true)}>Add students</Button><Button icon={Pencil} onClick={()=>setDraft({...group})}>Edit</Button><button className="hero-icon danger" type="button" title="Delete group" aria-label="Delete group" onClick={async()=>{if(confirm(`Delete ${group.name}?`)){const removed=await actions.deleteGroup(group.id);if(removed)setSelectedId("");}}}><Trash2 size={18}/></button></div></section><div className="detail-tabs"><button className="active">Overview</button><button>Students</button><button>Attendance</button><button>Grades</button><button>Payments</button></div>
    <section className="group-detail-grid"><article className="detail-card member-card"><header><h2>Members ({members.length})</h2><button type="button" onClick={()=>setMembersOpen(true)}>Manage</button></header>{members.map((student)=><div className="member-row" key={student.id}><span className="profile-avatar tiny">{initials(student.fullName)}</span><span><strong>{student.fullName}</strong><small>{student.isIndividual?"Individual + group":"Group student"}</small></span>{student.isIndividual?<em>Individual</em>:null}</div>)}{!members.length?<p>No students assigned yet.</p>:null}</article><article className="detail-card next-class"><header><h2>Group schedule</h2><Clock3 size={18}/></header><strong>{group.scheduleRoom||"Not scheduled"}</strong><p>{group.subject||"No subject set"}</p><Button variant="primary" onClick={()=>navigate("classes")}>Log a class</Button></article><article className="detail-card"><header><h2>Attendance</h2><CalendarDays size={18}/></header><div className="large-stat">{pct(summary.attendance)}</div><p>Average attendance</p></article><article className="detail-card"><header><h2>Performance</h2><TrendingUp size={18}/></header><div className="large-stat">{pct(summary.averageGrade)}</div><p>Latest group average</p></article><article className="detail-card"><header><h2>Outstanding balances</h2></header><div className="large-stat">{money(summary.outstanding)}</div><p>Across current members</p></article><article className="detail-card quick-list"><header><h2>Quick actions</h2></header><button type="button" onClick={()=>navigate("classes")}>Log group class <ChevronRight size={16}/></button><button type="button" onClick={()=>navigate("grades")}>Add group grades <ChevronRight size={16}/></button><button type="button" onClick={()=>navigate("payments")}>View payments <ChevronRight size={16}/></button></article></section>
    <Drawer open={membersOpen} onClose={()=>setMembersOpen(false)} title={`Manage ${group.name}`} description="Students can belong to more than one group."><div className="member-picker">{state.students.map((student)=><label key={student.id}><input type="checkbox" checked={(student.groupIds||[]).includes(group.id)} onChange={()=>toggleMember(student)}/><span className="profile-avatar tiny">{initials(student.fullName)}</span><span><strong>{student.fullName}</strong><small>{student.isIndividual?"Also takes individual classes":"Group enrollment"}</small></span></label>)}</div></Drawer><Drawer open={Boolean(draft)} onClose={()=>setDraft(null)} title="Edit group" footer={<><Button onClick={()=>setDraft(null)}>Cancel</Button><Button variant="primary" onClick={save}>Save group</Button></>}>{draft?<GroupEditor draft={draft} setDraft={setDraft}/>:null}</Drawer></div>;
  return <div className="page"><div className="page-heading"><div><h1>Groups</h1><p>Open any group to see its members, schedule, progress, and balances.</p></div><Button variant="primary" icon={Plus} onClick={()=>setDraft({...EMPTY})}>Add group</Button></div><label className="page-search"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search groups"/></label><section className="group-list">{filtered.map((item)=>{const itemSummary=derived.groups.find((row)=>row.id===item.id)||{};return <button className="group-row" key={item.id} type="button" onClick={()=>setSelectedId(item.id)}><span className="group-emblem small">{item.name.slice(0,1).toUpperCase()}</span><span className="group-main"><strong>{item.name}</strong><small>{item.scheduleRoom||item.subject||"Schedule not set"}</small></span><span><small>Students</small><strong>{itemSummary.activeStudents||0}</strong></span><span><small>Attendance</small><strong>{pct(itemSummary.attendance)}</strong></span><span><small>Ideal revenue</small><strong>{money(itemSummary.idealRevenue)}</strong></span><ChevronRight size={18}/></button>})}{!filtered.length?<div className="empty-box"><UsersRound size={28}/><h2>No groups yet</h2><p>Create your first class group.</p></div>:null}</section><Drawer open={Boolean(draft)} onClose={()=>setDraft(null)} title={draft?.id?"Edit group":"Add group"} footer={<><Button onClick={()=>setDraft(null)}>Cancel</Button><Button variant="primary" onClick={save}>Save group</Button></>}>{draft?<GroupEditor draft={draft} setDraft={setDraft}/>:null}</Drawer></div>;
}
